all:
  hosts:
    node1:
      ansible_host: 164.92.211.246
      ip: 164.92.211.246
      access_ip: 164.92.211.246
    node2:
      ansible_host: 167.71.15.149
      ip: 167.71.15.149
      access_ip: 167.71.15.149
    node3:
      ansible_host: 104.248.85.129
      ip: 104.248.85.129
      access_ip: 104.248.85.129
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
